# Generated by Django 5.2.11 on 2026-05-01 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="instructions",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cooking_time",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="price",
        ),
        migrations.AddField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(default=""),
        ),
    ]
